---
- hosts: all
  vars:
    http_port: 80
    max_clients: 200
    jk_server_name: 'http://10.127.41.162:8080'
    jk_rest_api_url: '/kyc/rest/getDelayedHelloWorld/deviceId/1/delay/10'
    jk_auth_user: 'admin'
    jk_auth_password: 'onPrem@123'
  remote_user: root
  tasks:
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest
  - name: write the apache index  file
    template:
      src: html/after.html
      dest: /var/www/html/index.html
    notify:
    - restart apache
  - name:
    shell:  "curl -f -H 'Content-Type: application/json' -XPOST --user admin:{{ jk_auth_password }} http://10.127.41.162/kyc/rest/getDelayedHelloWorld/deviceId/1/delay/10"
    when: inventory_hostname == 'localhost'
  
  - name: ensure apache is running
    service:
      name: httpd
      state: started
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted

