---
- hosts: all
  vars:
    http_port: 80
    max_clients: 200
    jk_server_name: 'http://10.127.41.162:8080'
    jk_rest_api_url: '/kyc/rest/getDelayedHelloWorld/deviceId/1/delay/10'
    jk_auth_user: 'admin'
    jk_auth_password: 'onPrem@123'
  environment:
    http_proxy: 'http://proxy.esl.cisco.com:80'
    no_proxy: 'localhost,127.0.0.0,10.127.41.162'
    https_proxy: 'http://proxy.esl.cisco.com:80'
  remote_user: root
  tasks:
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest
  - name: write the apache index  file
    template:
      src: html/after.html
      dest: /var/www/html/index.html
    notify:
    - restart apache
  - name: check if vhost is present
    uri:
      url: "{{ jk_server_name }}/{{ jk_rest_api_url }}"
      method: GET
      user: "{{ jk_auth_user }}"
      password: "{{ jk_auth_password }}"
      force_basic_auth: yes
      status_code: 200,404
      timeout: 10
    register: request_vhost
  - name: debug
    debug:
      var: request_vhost
  - name: create vhost
    uri:
      url: "{{ jk_server_name }}/{{ jk_rest_api_url }}"
      method: PUT
      HEADER_Content-Type: "application/json"
      user: "{{ jk_auth_user }}"
      password: "{{ jk_auth_password }}"
      force_basic_auth: yes
      status_code: 204
      timeout: 20
    when:
      - request_vhost.status == 404
  - name: ensure apache is running
    service:
      name: httpd
      state: started
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted

